module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        darkGreen: '#21C465',
        red: '#CC3333',
        offWhite: '#F5F0E8',
        navy: '#1C3D5A',
        navyDark: '#111f2e',
        navyDeep: '#0b1622',
        navyMid: '#1a3550',
        navyLight: '#254e72',
        orange: '#E8742A',
        orangeDark: '#c45e1a',
        orangeLight: '#f08c47',
        teal: '#2E7A8C',
        tealLight: '#3a9ab0',
        tealDim: 'rgba(46,122,140,0.08)',
        offWhite2: '#e4ddd0',
        muted: '#7090aa',
        muted2: '#4a6880',
        cardBg: 'rgba(255,255,255,0.04)',
        cardBorder: 'rgba(255,255,255,0.07)',
      },
      fontFamily: {
        playfairDisplayBold: ['Playfair Display Bold', 'serif'],
        playfairDisplayMedium: ['Playfair Display Medium', 'serif'],
        playfairDisplayRegular: ['Playfair Display Regular', 'serif'],
        playfairDisplaySemiBold: ['Playfair Display SemiBold', 'serif'],
        playfairDisplayBlack: ['Playfair Display Black', 'serif'],
        playfairDisplayExtraBold: ['Playfair Display ExtraBold', 'serif'],
        crimsonProRegular: ['Crimson Pro Regular', 'serif'],
        crimsonProSemiBold: ['Crimson Pro SemiBold', 'serif'],
        crimsonProMedium: ['Crimson Pro Medium', 'serif'],
        crimsonProBold: ['Crimson Pro Bold', 'serif'],
        crimsonProExtraBold: ['Crimson Pro ExtraBold', 'serif'],
        dmBold: ['DM Sans Bold', 'sans-serif'],
        dmMedium: ['DM Sans Medium', 'sans-serif'],
        dmRegular: ['DM Sans Regular', 'sans-serif'],
        dmSemiBold: ['DM Sans SemiBold', 'sans-serif'],
      },
      fontSize: {
        heading: '35px',
      },
    },
  },
  plugins: [],
};
